language: dart

dist: bionic

dart:
  - stable
  - beta
  - dev

jobs:
  allow_failures:
    - dart: dev
    - dart: beta
  fast_finish: true

dart_task:
  - test
  - dartfmt
  - dartanalyzer: --fatal-warnings .

cache:
  directories:
    - $HOME/.pub-cache
