name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable, beta, dev]

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: "Lint: Code formatting"
        run: dart format --output=none --set-exit-if-changed .

      - name: "Lint: Analyze project source"
        run: dart analyze --fatal-warnings .

      - name: "Test: Run tests"
        run: dart test
